version: '3'
services:
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
      - MONGO_PROD_USER=IrfanProject
      - MONGO_PROD_PASS=AVOID12345
      - MONGO_PROD_IP=cluster0.bbsb6.mongodb.net
    command: node index.js